### ISSUE TITLE
Add remove_stop words parameter to API

### ISSUE THREAD

**Issue by quillcraftsman** [findsimilar/demo#13]
In find_similar v1.2.0 `stop_words` parameter has been added. It will be great to add this parameter to API

**Comment by HammadRafique29** [comment]
I have gone through all the code, found some bugs, and fixed them. Now `find_similar_api `with **remove_stops_words** is working perfectly.

Here is the following things to be done for proper execution. 

-  `py manage.py runserver` throws an error ('inspect' has no attribute 'getargspec'.)
-   Above error is because `getargspec` is removed from **pymorphy2**.  I have Opened an issue, with pull request on pymorphy repo [Fixed #167](https://github.com/pymorphy2/pymorphy2/pull/167)
- **Find_Similar** using latest version with updated `remove_stopwords` functionality. But **find_similar_demo** `requirements.txt` contains the outdated requirement
- Added some code in files `serializers.py` for passing remove_stopwords argument.
- Increases the effeciency of **stop_words** using `nltk.stopwords`

After all of these above steps, `find_similar_demo` is running perfectly. In following output by passing `remove_stopwords=true` string **"is"** in text is removed

![image](https://github.com/findsimilar/demo/assets/112252001/d30c81fb-a7ee-4bf8-9439-9bd10d8d6622) ![image](https://github.com/findsimilar/demo/assets/112252001/d1dafff0-e427-4d28-b0ef-df0740134721)
